AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'python3.10

  Sample SAM Template for sam-app-sdxl

  '
Globals:
  Function:
    Timeout: 180
    MemorySize: 8000
  Api:
    BinaryMediaTypes:
    - image/png
    - image/jpg
    - image/jpeg
Resources:
  HelloSDXLFunction:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
      - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess
      MemorySize: 10240
      PackageType: Image
      Architectures:
      - x86_64
      Events:
        HelloSDXL:
          Type: Api
          Properties:
            Path: /model-gallery
            Method: post
      Environment:
        Variables:
          ENDPOINT_NAME: sdxl-1-jumpstart
      ImageUri: hellosdxlfunction:python3.10-v1
    Metadata:
      DockerContext: /Users/lindarr/environment/sam-app-sdxl/hello_sdxl
      DockerTag: python3.10-v1
      Dockerfile: Dockerfile
      SamResourceId: HelloSDXLFunction
Outputs:
  HelloSDXLApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/model-gallery/
  HelloSDXLFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloSDXLFunction
      - Arn
  HelloSDXLFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - HelloSDXLFunctionRole
      - Arn
